# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "ManiG / %s"
og_image: /img/og_manig.png
author: ManiG
favicon: /img/favicon.jpg
description: QA Manager & Curious about NueJs
port: 8083

# OG image
origin: https://nuejs.pages.dev
og: /img/og.jpg


navigation:
  header:
    - ManiG: /
    - Contact: /contact/

  footer:
    - © ManiG: /

    - image: /img/twitter.svg
      url: //x.com/meetmanig
      alt: Twitter (X) profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/Mani-QA/nuejsblog
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/manivannang
      alt: LinkedIn profile
      size: 22 x 22
